
package rs.ftn.xws.booking.accomodationwebservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AccomodationWebService", targetNamespace = "http://booking.xws.ftn.rs/accomodationWebService", wsdlLocation = "https://localhost:8443/services/AccomodationWebService?wsdl")
public class AccomodationWebService
    extends Service
{

    private final static URL ACCOMODATIONWEBSERVICE_WSDL_LOCATION;
    private final static WebServiceException ACCOMODATIONWEBSERVICE_EXCEPTION;
    private final static QName ACCOMODATIONWEBSERVICE_QNAME = new QName("http://booking.xws.ftn.rs/accomodationWebService", "AccomodationWebService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://localhost:8443/services/AccomodationWebService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACCOMODATIONWEBSERVICE_WSDL_LOCATION = url;
        ACCOMODATIONWEBSERVICE_EXCEPTION = e;
    }

    public AccomodationWebService() {
        super(__getWsdlLocation(), ACCOMODATIONWEBSERVICE_QNAME);
    }

    public AccomodationWebService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACCOMODATIONWEBSERVICE_QNAME, features);
    }

    public AccomodationWebService(URL wsdlLocation) {
        super(wsdlLocation, ACCOMODATIONWEBSERVICE_QNAME);
    }

    public AccomodationWebService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACCOMODATIONWEBSERVICE_QNAME, features);
    }

    public AccomodationWebService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AccomodationWebService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AccomodationWebServiceSoap
     */
    @WebEndpoint(name = "AccomodationWebServicePort")
    public AccomodationWebServiceSoap getAccomodationWebServicePort() {
        return super.getPort(new QName("http://booking.xws.ftn.rs/accomodationWebService", "AccomodationWebServicePort"), AccomodationWebServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AccomodationWebServiceSoap
     */
    @WebEndpoint(name = "AccomodationWebServicePort")
    public AccomodationWebServiceSoap getAccomodationWebServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://booking.xws.ftn.rs/accomodationWebService", "AccomodationWebServicePort"), AccomodationWebServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACCOMODATIONWEBSERVICE_EXCEPTION!= null) {
            throw ACCOMODATIONWEBSERVICE_EXCEPTION;
        }
        return ACCOMODATIONWEBSERVICE_WSDL_LOCATION;
    }

}
