
package rs.ftn.xws.booking.test;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TestServiceSoap", targetNamespace = "http://booking.xws.ftn.rs/test")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TestServiceSoap {


    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "testMethod", targetNamespace = "http://booking.xws.ftn.rs/test", className = "rs.ftn.xws.booking.test.TestMethod")
    @ResponseWrapper(localName = "testMethodResponse", targetNamespace = "http://booking.xws.ftn.rs/test", className = "rs.ftn.xws.booking.test.TestMethodResponse")
    public String testMethod();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "uploadMultiple", targetNamespace = "http://booking.xws.ftn.rs/test", className = "rs.ftn.xws.booking.test.UploadMultiple")
    @ResponseWrapper(localName = "uploadMultipleResponse", targetNamespace = "http://booking.xws.ftn.rs/test", className = "rs.ftn.xws.booking.test.UploadMultipleResponse")
    public void uploadMultiple(
        @WebParam(name = "arg0", targetNamespace = "")
        UploadModelXsd arg0);

}
